create table municipios (
	id bigint not null auto_increment,
    municipio varchar(45) not null,
    estado_id bigint not null,
    primary key (id)
);

insert into municipios values
-- Aguascalientes
	(1, 'Aguascalientes', 1),
    (2, 'Asientos', 1),
    (3, 'Calvillo', 1),
    (4, 'Cosío', 1),
    (5, 'El Llano', 1),
    (6, 'Jesús María', 1),
    (7, 'Pabellón de Arteaga', 1),
    (8, 'Rincón de Romos', 1),
    (9, 'San Francisco de los Romo', 1),
    (10, 'San José de Gracia', 1),
    (11, 'Tepazalá', 1),
-- Baja California
	(12, 'Ensenada', 2),
    (13, 'Mexicali', 2),
    (14, 'Playas de Rosarito', 2),
    (15, 'San Felipe', 2),
    (16, 'San Quintín', 2),
    (17, 'Tecate', 2),
    (18, 'Tijuana', 2),
-- Baja California Sur
	(19, 'Comondú', 3),
    (20, 'La Paz', 3),
    (21, 'Loreto', 3),
    (22, 'Los Cabos', 3),
    (23, 'Mulegé', 3),
-- Campeche
	(24, 'Calakmul', 4),
    (25, 'Calkiní', 4),
    (26, 'Campeche', 4),
    (27, 'Candelaria', 4),
    (28, 'Carmen', 4),
    (29, 'Champotón', 4),
    (30, 'Dzitbalché', 4),
    (31, 'Escárcega', 4),
    (32, 'Hecelchakán', 4),
    (33, 'Hopelchén', 4),
    (34, 'Palizada', 4),
    (35, 'Seybaplaya', 4),
    (36, 'Tenabo', 4),
-- Coahuila de zaragoza
	(37, 'Abasolo', 5),
    (38, 'Acuña', 5),
    (39, 'Allende', 5),
    (40, 'Arteaga', 5),
    (41, 'Candela', 5),
    (42, 'Castaños', 5),
    (43, 'Cuatro Ciénegas', 5),
    (44, 'Escobedo', 5),
    (45, 'Francisco I. Madero', 5),
    (46, 'Frontera', 5),
    (47, 'General Cepeda', 5),
    (48, 'Guerrero', 5),
    (49, 'Hidalgo', 5),
    (50, 'Jiménez', 5),
    (51, 'Juárez', 5),
    (52, 'Lamadrid', 5),
    (53, 'Matamoros', 5),
    (54, 'Monclova', 5),
    (55, 'Morelos', 5),
    (56, 'Múzquiz', 5),
    (57, 'Nadadores', 5),
    (58, 'Nava', 5),
    (59, 'Ocampo', 5),
    (60, 'Parras', 5),
    (61, 'Piedras Negras', 5),
    (62, 'Progreso', 5),
    (63, 'Ramos Arizpe', 5),
    (64, 'Sabina', 5),
    (65, 'Sacramento', 5),
    (66, 'Saltillo', 5),
    (67, 'San Buenaventura', 5),
    (68, 'San Juan de Sabinas', 5),
    (69, 'San Pedro', 5),
    (70, 'Sierra Mojada', 5),
    (71, 'Torreón', 5),
    (72, 'Viesca', 5),
    (73, 'Villa Unión', 5),
    (74, 'Zaragoza', 5),
-- Colima
	(75, 'Armería', 6),
    (76, 'Colima', 6),
    (77, 'Comala', 6),
    (78, 'Coquimatlán', 6),
    (79, 'Cuauhtémoc', 6),
    (80, 'Ixtlahuacán', 6),
    (81, 'Manzanillo', 6),
    (82, 'Minatitlán', 6),
    (83, 'Tecomán', 6),
    (84, 'Villa de Álvarez', 6)
;